[package]
name = "num-to"
version = "1.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Quelfth/num-to"
description = "Number conversions without using as."

[dependencies]
